### ISSUE TITLE
Event ID 27

### ISSUE THREAD

**Issue by VadimKutia** [ion-storm/sysmon-config#21]
Hello! Please tell me where did the Event ID 27: FileBlockExecutable go from the config? Was it removed on purpose?

**Comment by NerbalOne** [comment]
Hey @VadimKutia. It was originally moved to a separate blocking config due to reports of it causing interference with Windows updates. (https://github.com/ion-storm/sysmon-config/commit/a99afce0868b51bd5d06bd69a38eab55456a20f2#diff-b7cb7b23892562ba7aecfd353d52b1b244c37e0e15ceb0a915dfbb16276078bc) For now I don't believe we will have a separate blocking config that contains Event ID 27 and have since removed it. The link above does contain the old rules for Event ID 27 before it was removed so you could add that to your config if you so choose. For now we will just focus on the main config that does not include Event ID 27.
